### ISSUE TITLE
Wisconsin county test data missing since 2020-09-16

### ISSUE THREAD

**Issue by mikelehen** [valorumdata/cmdc-tools#119]
We seem to have lost negative_tests_total and positive_tests_total for many Wisconsin counties starting 2020-09-15

Milwaukee (FIPS 55079):
```
curl -X GET "https://api.covidcountydata.org/covid_us?dt=gt.%222020-09-01%22&location=eq.55079&variable=eq.positive_tests_total&limit=100" \
 -H "Accept: application/json, application/vnd.pgrst.object+json, text/csv" \
 -H "Range-Unit: items" 
```

Last entry is:
```
  {
    "dt": "2020-09-15",
    "location": 55079,
    "variable": "positive_tests_total",
    "value": 25721,
    "fips": "55079"
  }
```

Other missing counties include: 55089, 55093, etc.

**Comment by sglyon** [comment]
Thanks @mikelehen 

@cc7768 I took a look at this. The data exists in the argcis tables here: https://data.dhsgis.wi.gov/datasets/covid-19-historical-data-table/data

but we are indeed only getting up to 2020-09-15 when the scraper runs. I believe the problem might be with the `ArcGIS.get_all_sheet_to_df` method.

I'm not sure how we determined the stopping criterion for the `while` loop in that function. Would you be willing to take a look?

**Comment by sglyon** [comment]
Ref: see here for filtered view on their data page: https://data.dhsgis.wi.gov/datasets/covid-19-historical-data-table/data?where=DATE%20%3E%3D%20TIMESTAMP%20%272020-09-15%2000%3A00%3A00%27%20AND%20DATE%20%3C%3D%20TIMESTAMP%20%272020-10-04%2023%3A59%3A59%27%20AND%20GEOID%20%3D%20%2755079%27

**Comment by sglyon** [comment]
I wonder if this url is permanent: https://prod-hub-indexer.s3.amazonaws.com/files/b913e9591eae4912b33dc5b4e88646c5/10/d9d9616607ea39816fc456a185e7e17a2aa03d4e/3857/b913e9591eae4912b33dc5b4e88646c5_10_d9d9616607ea39816fc456a185e7e17a2aa03d4e_3857.csv

**Comment by cc7768** [comment]
It looks like WI has stopped updating their ArcGIS services. It says,

> The Wisconsin Department of Health Services is no longer providing daily data updates to ArcGIS Online's REST environment. Please refer all applications to the WI DHS GIS server environment: https://dhsgis.wi.gov/server/rest/services/DHS_COVID19 Technical questions about this change can be directed to: DHS_GIS@dhs.wisconsin.gov

These updates must have stopped on September 15.

**Comment by cc7768** [comment]
Found where they're hosting the new database. See PR #120
