### ISSUE TITLE
North Dakota county data coming from Massachusetts source?

### ISSUE THREAD

**Issue by mikelehen** [valorumdata/cmdc-tools#134]
```
curl -X GET "https://api.covidcountydata.org/covid_sources?fips=eq.38017&limit=100" \
 -H "Accept: application/json, application/vnd.pgrst.object+json, text/csv" \
 -H "Range-Unit: items" 
```

Returns:
```
[
  {
    "location": 38017,
    "fips": "38017",
    "name": "Cass County",
    "state_name": "North Dakota",
    "variable": "cases_total",
    "source": "https://www.mass.gov/info-details/covid-19-response-reporting#covid-19-daily-dashboard-"
  },
...
```

Each variable has https://www.mass.gov/info-details/covid-19-response-reporting#covid-19-daily-dashboard- as the source, even though this is the Massachusetts COVID-19 dashboard...  What's up?

**Comment by sglyon** [comment]
Thanks @mikelehen this is a typo in our scraper for logging the source.

The data is indeed coming from North Dakota (so that is not an issue), but we were logging it as coming from the MA dashboard

We've fixed this in #135
