### ISSUE TITLE
NE scraper broken

### ISSUE THREAD

**Issue by sglyon** [valorumdata/cmdc-tools#82]
The NE (Nebraska) scraper has `.get_state` and `.get_county`

The county one broke a few hours ago (as of 2020-07-10 at 18:42 EST)

It is an ARCGIS dashboard. When I poked around the dashboard I couldn't find the county level variables we used to gather from that dashboard. 

```
[
                "hospital_beds_in_use_any",
                "icu_beds_in_use_any",
                "recovered_total",
                "deaths_total",
                "ventilators_in_use_any",
                "positive_tests_total",
                "hospital_beds_capacity_count",
                "icu_beds_capacity_count",
                "ventilators_capacity_count",
                "recovered_total",
                "dt",
            ]
```

@cc7768  or @tlyon3 you are objectively more familiar with ARCGIS and our tools.  Will you take a look at the dash and see if you can figure out if that data is still available?

**Comment by cc7768** [comment]
See #83
